### ISSUE TITLE
幅オプションの追加

### ISSUE THREAD

**Issue by kobi32768** [Qman11010101/narou2kakuyomu#41]
ブラウザウィンドウ最大化時に表示される幅がやや狭いので, 表示幅を変更するオプションを追加する.
予定しているものはデフォルト幅の `1x`, `1.5x`, `2x`.

**Comment by Qman11010101** [comment]
細かい設定として%でもいけたらうれしいかもしれない

**Comment by kobi32768** [comment]
機能として % 指定は充分アリ
ただ UI 設計が難しそうなので要検討

横に 3 つ並んだものは現状ないので `1.25x` を追加するのもアリかもしれない

**Comment by Qman11010101** [comment]
横に並べる分には多分何個でもいい感じになるようにCSS組まれてるはずだからそこらへんは気にせずともOKだと思われ

**Comment by kobi32768** [comment]
デザインと気分の都合です……
