### ISSUE TITLE
カクヨムの各テーマの色を取得する

### ISSUE THREAD

**Issue by Qman11010101** [Qman11010101/narou2kakuyomu#5]
カラーコードが分かればOK

**Comment by kobi32768** [comment]
調べてきました

white
- bg: #ffffff
- tx: #222222

black
- bg: #171b1d
- tx: #f0f0f0

kinari
- bg: #f7f6eb
- tx: #292826

blue
-  bg: #dfecf4
- tx: #262829

**Comment by Qman11010101** [comment]
:+1:
